{{- if .Values.application.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: {{ .Release.Name }}
    app_version: {{ .Values.application.image.tag }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.application.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.application.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.application.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.application.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
