{{- if .Values.application.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: {{ .Release.Name }}
    app_version: {{ .Values.application.image.tag }}
  annotations:
  {{- range $key, $value := .Values.application.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.application.ingress.host }}
    http:
      paths:
        - path: {{ .Values.application.ingress.rootPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ $.Release.Name }}
              port: 
                number: 80
        {{- range $path := .Values.application.ingress.additionalPaths }}
        - path: {{ $path.path }}
          pathType: Prefix
          backend:
            service:
              name: {{ $path.serviceName }}
              port:
                number: {{ $path.servicePort }}
        {{- end }}
  {{- if .Values.application.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.application.ingress.host }}
    {{- if .Values.application.ingress.tls.secret }}
    secretName: "{{ .Values.application.ingress.tls.secret}}"
    {{- else }}
    secretName: {{ $.Release.Name }}
    {{- end }}
  {{- end }}
{{- end -}}
